### ISSUE TITLE
Void Task

### ISSUE THREAD

**Issue by btraas** [BrayDong/COMP4711_Lab056#10]
There is only the one CSV file for this app, data/tasks.csv.

I suggest naming models after the "tables", which would usually mean the plural of the entity name that a "table" pertains to. For this lab, that suggests application/models/Tasks.php ...

class Tasks extends CSV_Model {

        public function __construct()
        {
                parent::__construct(APPPATH . '../data/tasks.csv', 'id');
        }

}
The filename above is a mouthful, starting at the application folder, moving up one folder, and then drilling down into the data folder. It would be cleaner if we had a DATAPATH constant to use, and you are free to do that (but not required to), for instance setting that in applicaiton/config/constants.php. If you choose to do this, do not set absolute paths, as they may not work on your team mates' platforms or mine!

We inherit a whack of functionality from CSV_Model ... CRUD methods, searching methods, etc. Check out core/CSV_Model.php, if you haven't done so already.

Note: In the constructor above, I expressly specified the "table" name (case sensitive) and the "column" to use as a primary key. If these were not provided, the base model constructor will assume that the origin ("table" filename) is the same as the class name, and that the unique identifier "column" is id (that would be the primary key in an RDB table).

Your webapp homepage should still load without change, but without errors.

**Comment by kdw313** [comment]
Void Task
